### ISSUE TITLE
Failed to activate the center-screen package

### ISSUE THREAD

**Issue by exalted** [mlitvk/center-screen#1]
I simply run center screen from the command palette.

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [center-screen](https://github.com/mlitbk/center-screen) package, v0.2.1
### Stack Trace

Failed to activate the center-screen package

```
At Cannot find module 'src/editor-view'

Error: Cannot find module 'src/editor-view'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at new CenterScreen (/Users/exalted/.atom/packages/center-screen/lib/center-screen.coffee:47:18)
  at /Users/exalted/.atom/packages/center-screen/lib/main.coffee:12:13
  at WorkspaceView.module.exports.WorkspaceView.eachEditorView (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace-view.js:92:9)
  at Object.module.exports.activate (/Users/exalted/.atom/packages/center-screen/lib/main.coffee:10:24)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:740:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:219:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```
### Commands

```
  2x -2:31.1.0 core:backspace (atom-text-editor.editor.mini)
  2x -2:30.4.0 core:confirm (atom-text-editor.editor.mini)
  2x -1:31.7.0 core:backspace (atom-text-editor.editor.mini)
     -0:23.7.0 pane:show-next-item (atom-text-editor.editor.mini)
     -0:22.3.0 command-palette:toggle (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:16.9.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:16.9.0 core:cancel (atom-text-editor.editor.mini)
     -0:08.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:08.1.0 core:move-to-top (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:07.9.0 find-and-replace:show (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:07.0 core:confirm (atom-text-editor.editor.mini)
     -0:06.7.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:06.7.0 core:cancel (atom-text-editor.editor.mini)
     -0:05.8.0 command-palette:toggle (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
     -0:02.8.0 core:confirm (atom-text-editor.editor.mini)
     -0:02.8.0 center-screen:center-screen (atom-text-editor.editor.cursor-block.cursor-line-fix.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "markdown-format",
      "syntax-settings",
      "autocomplete",
      "deprecation-cop",
      "autocomplete-paths",
      "archive-view",
      "background-tips",
      "bookmarks",
      "image-view"
    ],
    "projectHome": "/Users/exalted/Development",
    "followSymlinks": true,
    "themes": [
      "one-light-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-emojis, v2.2.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.12.0
autocomplete-snippets, v1.2.0
block-cursor, v0.12.4
center-screen, v0.2.1
highlight-selected, v0.9.2
language-csharp, v0.5.0
linter, v0.12.1
linter-rubocop, v0.2.2

# Dev
No dev packages
```

**Comment by prodelay** [comment]
Still problem at:

**Atom Version**: 0.209.0
**System**: Mac OS X 10.10.3
**Thrown From**: [center-screen](https://github.com/mlitbk/center-screen) package, v0.2.1

**Comment by FGRibreau** [comment]
:+1:

**Comment by ghost** [comment]
My stack trace seems to look a bit differently

``` coffee
TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/sthiel/.atom/packages/center-screen/lib/main.coffee:7:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

**Comment by kdodia** [comment]
Errors on Atom launch:

``` coffeescript
  activate: ->
    atom.workspaceView.command 'center-screen:toggle-follow-cursor', =>          <--
      @toggleFollowCursor()
```

**Atom Version**: 1.6.1
**System**: Mac OS X 10.10.5
**Thrown From**: [center-screen](https://github.com/mlitbk/center-screen) package, v0.2.1

### Stack Trace

Failed to activate the center-screen package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/kdodia/.atom/packages/center-screen/lib/main.coffee:7:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:181:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:155:32
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:148:26
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:145:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:526:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:507:29
    at Config.module.exports.Config.transactAsync (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:502:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:485:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:688:21)
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
  5x -0:04.1.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
```

### Config

``` json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
arpeggio, v1.1.2
atom-2048, v3.1.0
center-screen, v0.2.1
clipboard-plus, v0.5.1
file-icons, v1.6.19
git-wip, v0.2.2
minimap, v4.21.0
minimap-autohide, v0.10.1
minimap-codeglance, v0.4.5
minimap-hide, v0.3.0
minimap-pigments, v0.2.0
pigments, v0.26.0
quick-highlight, v0.3.10
scroll-percentage, v1.2.1
set-syntax, v0.3.0
term3, v0.21.4
vim-mode-plus, v0.28.0
vim-mode-plus-jasmine-increase-focus, v0.2.0
vim-mode-plus-move-selected-text, v0.4.1
vim-mode-plus-move-to-symbols, v0.1.4
vim-mode-plus-replace-with-execution, v0.1.1
vim-mode-plus-subword-movement, v0.2.2
vim-modeline, v0.4.0

# Dev
No dev packages
```

**Comment by ashnur** [comment]
Any ideas on how to fix this?

**Comment by taoeffect** [comment]
> Any ideas on how to fix this?

Install https://github.com/shaunwei/atom-center-screen

**Comment by ashnur** [comment]
@taoeffect 
1. installing a different package is not in any way the same as fixing this one, in what universe would that be even acceptable as an answer? If my question would've been "is there an alternative?", then I would understand, but right now it seems that you are just being ignorant 
2. And I say ignorant doubly so because the package you linked seems to lack the feature I was interested in: the ability to automatically follow the cursor, keeping the selected line centered

But yeah, I bet it felt good for 10 seconds that you could give me something from google.

**Comment by kdodia** [comment]
> Any ideas on how to fix this?

Delete your account.

P.S. Thanks @taoeffect, I appreciated the pointer. :3

**Comment by josephfusco** [comment]
+1

**Comment by cwoac** [comment]
It's using the old style command accessing, broadly speaking it needs a rewrite, albeit not a huge one (see here: https://discuss.atom.io/t/replacement-for-atom-workspaceview-command/13636) for discussion.

If nobody else does, I may have a stab at it, but probably won't have time for a while.

**Comment by exalted** [comment]
I am going to close this, but please feel free to re-open if interested.

**Comment by ksandvik** [comment]
Still an issue, Atom 1.16 MacOSX 10.12.4: Failed to activate the center-screen package, cannot read property 'command' of undefined.

**Comment by ericychoi** [comment]
+1 on the same issue

**Comment by pciavald** [comment]
i'm getting the error on install 

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [center-screen](https://github.com/mlitbk/center-screen) package 0.2.1


### Stack Trace

Failed to activate the center-screen package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.activate (/packages/center-screen/lib/main.coffee:7:23)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:218:19)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:484:29
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:99:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:322:11)
    at /app.asar/src/buffered-process.js:343:11
    at /app.asar/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
angularjs 0.4.0 
ariake-dark-syntax 0.1.3 
atom-angular-material-snippets 1.3.0 
atom-material-syntax 1.0.6 
atom-material-ui 1.3.10 
autocomplete-angular-material 0.4.0 
center-screen 0.2.1 
hybrid-next-syntax 0.9.2 
language-ethereum 0.3.9 
linter-solidity 0.5.0 
minimap 4.28.2 
nord-atom-syntax 0.9.1 
nord-atom-ui 0.11.0 
relative-numbers 0.8.0 
todo-show 1.11.0 
vim-mode-plus 0.92.1 
vim-mode-plus-ex-mode 0.9.0 
```

**Comment by hiAndrewQuinn** [comment]
Still an issue. I'll see if I have some time this weekend to fix this, because the Follow Cursor thing is a killer feature.
